### ISSUE TITLE
UnicodeEncodeError with verbose switch set

### ISSUE THREAD

**Issue by tyrasd** [BikeCitizens/osm-regional-diffs#1]
moving over from https://github.com/jkirk/osm-regional-diffs/issues/5:

> When setting the verbose flag, the script crashes on my server:
> 
> ```
> VERBOSE: Traceback (most recent call last):
> File "./regional-diff.py", line 551, in 
> posm = PlanetOsm()
> File "./regional-diff.py", line 131, in init
> self.update()
> File "./regional-diff.py", line 514, in update
> self.__osmosis()
> File "./regional-diff.py", line 240, in __osmosis
> verboseprint(u"checking way-id „" + way_id + u"“")
> File "./regional-diff.py", line 45, in verboseprint
> print ("VERBOSE:", *args, file=sys.stderr)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u201e' in position 16: ordinal not in range(128)
> ```
> 
> After replacing all occurrences of u"foo" with "foo", it works for me. Using Python 2.7.3 (Ubuntu 12.04 package).

**Comment by tyrasd** [comment]
should be fixed in 673e09575015eaed7ba3d853e32b8eeb7e8d4887
